# SpeedRun configuration file.
# Please modify this before running for the first time.

# The world players should be teleported to when the game is over.
ReturnWorld: 'world'

# The game world.
GameWorld: 'SpeedRun'