name: SpeedRun
version: 1.3
main: org.mcuni.speedrun.SpeedRun
api-version: 1.19
authors: [ LewisMilburn, MCUniDev ]
description: A basic Speed Run plugin by MCUni.
website: https://dev.mcuni.org/speedrun
load: STARTUP
commands:
  speedrun:
    description: Main command
    usage: /<command>
    aliases: ['sr']
permissions:
  speedrun.admin:
    description: Gives access to all SpeedRun commands.